using System;
using System.Collections.Generic;
using System.Text;

namespace fiQ.Task.Models
{
	/// <summary>
	/// Container class for return data from TaskEngine's Execute function (representing execution of
	/// one or more TaskAdapter::ExecuteTask functions)
	/// </summary>
	public class TaskSetResult
	{
		#region Fields
		public StringBuilder LogMessage { get; } = new StringBuilder();
		private Dictionary<string, string> returnValues = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
		#endregion

		#region Properties
		/// <summary>
		/// Integer return value for overall result of adapter executions
		/// </summary>
		public int ReturnValue { get; set; } = -1;
		/// <summary>
		/// Collection of output/return values (key/value pairs) generated by task execution
		/// </summary>
		public IReadOnlyDictionary<string, string> ReturnValues
		{
			get { return returnValues; }
		}
		#endregion

		#region Methods
		/// <summary>
		/// Merge a collection of values into parameter set (overwriting, if necessary)
		/// </summary>
		public void MergeReturnValues(IReadOnlyDictionary<string, string> values)
		{
			foreach (var parm in values)
			{
				returnValues[parm.Key] = parm.Value;
			}
		}
		#endregion
	}
}
